### ISSUE TITLE
Tagging Patterns and Manipulating Tags

### ISSUE THREAD

**Issue by ghalestrilo** [tidalcycles/Tidal#641]
**Is your feature request related to a problem? Please describe.**
There is no easy way right now to apply arbitrary changes to a specific note *inside* a pattern from *outside*

1. Suppose I have the following pattern:
```haskell
d1
  $ n "<0 2 1 [1 <0 1>]>"
  # s "prcchord"
```
Now, if we want  just the second "0", in the third line, to be shifted one semitone up, this is what we have to do:
```haskell
d1
  $ n "<0 2 1 [1 <0 1>]>"
  # s "prcchord"
  # up "<0 0 0 [0 <1 0>]>"
```
Which is kind of silly. 

2. This also happens when writing tonal interchanges:
```haskell
p "piano"
  $ (note . scale "lydian") "{9 8 6 0 ~   9 8 6 2 3 4 3 4 5 4 5 6 ~   9 8 6 4 ~ }%8"
  # s "superpiano"
```
If we want the last segment of the phrase to be player over a major iii- chord every two beats, we have three options:
  1. Changing both **scale** and **root** with a pattern, like the first example
  2. Using `up` in the same fashion as above (painful for large patterns like this)
  3. Dropping scale, and rewriting everything chromatically (which is what I ended up doing)

**Describe the function/feature you'd like**
Using a tag/annotation-type feature, we could write the first example as:
```haskell
d1
  $ tag "mynote" (# up 1)
  $ n "<0 2 1 [1 <0&mynote 1>]>"
  # s "prcchord"
```
And this allows us to manipulate that specific beat with absolute control. `tag` receives the name of the tag and a function to apply over the matching tags. On the second example:

```haskell
p "piano"
  $ tag "ti" (down "<0 1>")
  $ (note . scale "lydian") "{9 8 6 0 ~   9 8 6 2 3 4 3 4 5 4 5 6&ti ~   9&ti 8 6&ti 4 ~ }%8"
  # s "superpiano"
```

Note that, for this example to work, `(down "0 1")` must be applied from outside the scope of `scale`, otherwise, it would not have the desired effect, and would be the same as writing:

```haskell
p "piano"
  $ (note . scale "lydian") "{9 8 6 0 ~   9 8 6 2 3 4 3 4 5 4 5 <6 5> ~   <9 8> 8 <6 5> 4 ~ }%8"
  # s "superpiano"
```

**Describe alternatives you've considered**
As mentioned above, whenever I want to achieve this behavior, I have to duplicate the pattern just to change the desired notes, and often mistype something in the process. I though of using `every` or `whenMod` but it seems contrived for the mentioned use-cases.

**Comment by jwaldmann** [comment]
You want names in expressions, and to substitute them with something.  The expression then denotes a function. 

The irony is that this problem is already solved in the host language (Haskell) from the very beginning, via lambda expressions.
```
d1 $ n ((\ x -> (slowcat [0, 2, 1, fastcat [1, slowcat [x,1]]])) 12)
  # s "superpiano"
```
Tidal's string mini-language does not have (names and) functions,
so you have to write long-form Haskell expressions, which may be inconvenient.

I believe there is an ongoing design discussion #530 . I don't know the current consensus and plan.

I am skeptical of the idea to re-introduce lambdas. We should then 
also check their scope and type (that is, re-implement type lambda calculus). If we don't, it'll be a language like Perl or Python - but these already exist.

We can perhaps make an `instance Read (Pattern a -> Pattern b)`
then the above might we written
```
d1 $ n ("<0 2 1 [1 < # 1>]>"  12)  -- this is function  application
  # s "superpiano"
```
Here we need concrete syntax for "the variable bound by the (invisible) lambda", I took `#` just as an example. 

The typing will be difficult: if the context demands `Pattern b`,
and the exprssion is an application of `Pattern a -> Pattern b` to `Pattern a`, then how should we (should the compiler) determine the `a`?

**Comment by ghalestrilo** [comment]
Substitution would be **incredible** as well (I see many, many use cases for that), but I think I described something simpler: a lambda to be called over the **outer pattern** whenever it reaches a matching tag. Sorry to create confusion with that.

I don't see it as an reimplementation of lambdas at all, I see it more as a higher-order "map-ish" function, that only applies a provided lambda to the overall pattern (like `every`, `sometimes`) when a condition is met (a tag comparison). Think of it this way: A lambda should be applied in place, so its value is returned during pattern-parsing time. From what I understand, `every` (ie.) doesn't do that. Instead, it applies a lambda to the pattern at appropriate times, defined by the first argument.

This `tag` function could also be just a wrapper to automatically build that `up "<0 0 0 [0 <1 0>]>"` line on the first example, for instance. That would do the job and keep it DRY. It can be even simpler to just return the `"<0 0 0 [0 <1 0>]>"` pattern, so we can use that on the outer pipe.

On a side-note, `n` and `note` are different things, so the example you described is slightly different than what I wrote. Imagine you want to change the `s` property on that note, for instance, and try to write the example again to see the difference.

Let me know if I'm missing something, but it seems like a simpler feature that addresses a very clear pain point, and could benefit the user. Also, thanks for linking that discussion on variables and substitution, that's an awesome feature and I'm looking forward to what gets decided there.

**Comment by jwaldmann** [comment]
I think we actually agree here?

> function, that only applies ... when a condition .. is met

the condition is that we are at a certain marked subterm, the function is the substitution. A "variable" is just a mark at a (leaf) subterm.

PS: I wasn't aware of the distinction between `n` and `note`, and I still don't get it from reading the Haskell source. Is this a SuperCollider/Dirt concept?
```
-- | specifies the sample or note number to be used
n :: Pattern Double -> ControlPattern
n = pF "n"
note :: Pattern Double -> ControlPattern
note = pF "note"
```
Can you suggest a better wording of the docs here? (Make a separate issue.)

**Comment by bgold-cosmos** [comment]
You can partly do this with a dummy "tag" parameter and the `fix` function, though to make it simple to use you have to define a new `grp` for everything you want to use it with:

```
tidal> tag = pI "tag"

tidal> ntag = grp [mF "n", mI "tag"]

tidal> fix (+ n 1) (tag 1) $ ntag "0 1 2 3:1"

(0>¼)|n: 0.0f
(¼>½)|n: 1.0f
(½>¾)|n: 2.0f
(¾>1)|n: 4.0f, tag: 1
```

**Comment by ghalestrilo** [comment]
Wow dude, huge catch! `n` is for sample index (like, the number of the actual file in the folder), and `note` (wrapper for `up`, I think) indicates the pitch at which they should be played. This should be doc'ed, I'll open an issue.

That said, yeah, I think we agree, but I still don't see how a substitution inside the argument of `n` could be able to change **anything** outside of the `n` scope (like `s`, or `up`, or `note`), which is kind of the point. What would you suggest?

**Comment by ghalestrilo** [comment]
I didn't know about `fix`

**Comment by ghalestrilo** [comment]
The `fix` + `grp` workaround works great. This is what I came up with:
```haskell
let tag = pI "tag"
    notetag = grp [mF "note", mI "tag"]
    n = grp [mF "n", mI "tag"]
    on tagname lambda = fix lambda (tag tagname)

d3
  $ on 1 ((# up 1) . (|* sus 0.99))
  $ on 2 (# up (-1))
  $ n "<0 2 1 [1 <0:1 1:2>]>"  # s "prcchord"
```

`on` becomes exactly what I was looking for. Unfortunately, it's limited by #639 , so it only works with constant, numerical values for tags. Still a pretty good solution for the time being.
@jwaldmann @bgold-cosmos I'll close this issue, then, ok?

**Comment by yaxu** [comment]
Let us know how practical this turns out to be. `fix` has done performance issues

**Comment by ghalestrilo** [comment]
@yaxu How do I properly stress-test this?

**Comment by yaxu** [comment]
@ghalestrilo have multiple instances of 'fix' running in one pattern.. As I remember, it eats a lot of cpu when you have 5-6 of them

**Comment by jwaldmann** [comment]
"eats cpu": see #564

**Comment by ghalestrilo** [comment]
The solution above does begin to lag after around 8 layers on a simple pattern (with `sometimesBy`), though I don't that many layers often. Worth looking into, though, I'll follow the discussion on the mentioned issue.
